#!/usr/bin/env python3
import time
import colors as c
snake = '''
                  _____ ____    ____  __  _    ___  
                 / ___/|    \  /    ||  |/ ]  /  _]
                (   \_ |  _  ||  o  ||  ' /  /  [_ 
                 \__  ||  |  ||     ||    \ |    _]
                 /  \ ||  |  ||  _  ||     \|   [_ 
                 \    ||  |  ||  |  ||  .  ||     |
Thats because the \___||__|__||__|__||__|\_||_____| snaaake ooh the snake! 
                                                                                                                                                         
'''

mushroom_time =1
count_length =0.3838387

c.clear_screen()

for verse in range(5):

    for badger in range (11):
        time.sleep(count_length)
        print(c.pink + 'Badgers :P' + c.reset)
    for mushroom in range (2):
        time.sleep(mushroom_time)
        print(c.blue + 'Mushroom' + c.red)
    c.clear_screen()

print(snake)

                                                                                                                                                               
