#!/usr/bin/env python3
import colors as c
print(c.clear)
print(c.yellow +  '''
Who would cross the Bridge of Death
Must answer me these questions three
'Ere the other side he see
''' + c.reset)
def ask(question):
    print(c.red + question + c.reset)
    name = input('>' + c.base3).lower().strip()
    print(c.reset)
    return name

name = ask('What is your name?')
quest = ask("What is your quest?")

if name in ['lancelot','galahad']:
    color = ask(c.blue + 'What is your favorite color?' + c.reset)
    if color in ['blue']:
        print('You may pass!')
    else:
        print('Game Over')
elif name in ['robin']:
    capitol = ask(c.blue + 'What is the capitol of Asseria!')
if name in ['arthur']:
    swallow = ask(c.orange + 'What is the air speed, velocity, of an unladen swallow?')


