#!/usr/bin/env python3
import colors as c
print(c.clear)
print(c.yellow +  '''
Who would cross the Bridge of Death
Must answer me these questions three
'Ere the other side he see
''' + c.reset)

print(c.red + 'What is your name?' + c.reset)
name = input('>').lower().strip()

print(c.green + 'What is your quest?' + c.reset)
quest = input('>')

if name in ['lancelot','galahad']:
    print('You scared bruh')
    print(c.blue + 'What is your favorite color?' + c.reset)
    color = input('>')




