#!/usr/bin/env python3

import colors as c
from utils import ask

print(c.clear)
print(c.pink + '''
Welcome to the pink fluffy
unicorns quiz game!!!!!!
'''  + c.reset)
 
   
def q1():   
    fur = ask('What is the color of a pink fluffy unicorns fur?')
    if fur == 'pink':
        return True
    return False

def q2():
    dance = ask('What do pink fluffy unicorns dance on?')
    if dance.startswith("rainbow"):
        return True
    return False


def q3():
    texture = ask('Please use one word to describe the texture of their magical fur?' + c.reset)
    if texture.startswith("smile"):
        return True
    return False

questions = [q1,q2,q3]

questions[0]()

