#!/usr/bin/env python3

import colors as c
import fluffy as quiz
import random

print(c.clear)
print(quiz.intro)

while quiz.questions:
    question_to_ask = random.choice(quiz.questions)
    is_correct = question_to_ask()
    if is_correct:
        quiz.questions.remove(question_to_ask)

