#!/usr/bin/env python3
import time
import colors as c
"""
Welcome to Gabe's amazing Timer, enjoy!
"""

h = 1
print(c.clear) 
while True:
    time.sleep(0.01)
    print (c.clear)
    print(c.magenta + '[Control-C to stop]' + c.reset, end=': ')
    h += 100
    print(h)
