#!/usr/bin/env python3

import random
import colors as c
print(c.clear + "")
print(c.red + 'Welcome to the magical magic EIGHTBALL!')
print(c.blue + 'PLZ ask question' + c.reset)
answer = input('>')

bruh =[
'):',
'Bruh?',
'No way',
'Eat a bagel and ask again',
'Yus man, YUS',
'If dinosaurs ate mustaches that would be yes',
'No, no, and NO',
'"smacks"',
'Why would you even ask that',
"Maybe, or maybe I'm lying to you",
'SHE STALKS',
'You are wrong if carpets fly',
'WHY are you asking ME',
'I dont even care man'
]
print(random.choice(bruh))
