#!/usr/bin/env python3

import colors as c
print('Do you like waffles?')

print('Do you like pancakes')

print('Do you like french toast?')

print('Doo doo do doo do we should eat a mouthful! WAFFLES!')
