#!/usr/bin/env python3

import colors as c

print(c.clear + c.red + 'Do you like waffles?' + c.reset)

waffles = input('>')


if waffles == 'yes':
    print(c.blue + 'Do you like pancakes?')
    pancakes = input('>')
    if pancakes == 'yes':
        print(c.green + 'Do you like frenchtoast?')
        frenchtoast = input('>')
        if frenchtoast == 'yes':
            print(c.orange + 'Doo do doo do doo we should eat a mouthful waffles!')
        else: 
            print('Well I like fenchtoast')
    else:
        print('Well I like pancakes!')
else:
    print('Well I like waffles!')
